#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 81
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  aux_sym_python_code_token1 = 1,
  aux_sym_python_code_token2 = 2,
  aux_sym_content_token1 = 3,
  anon_sym_LT = 4,
  anon_sym_GT = 5,
  anon_sym_LT_SLASH = 6,
  anon_sym_SLASH_GT = 7,
  anon_sym_LT_GT = 8,
  anon_sym_LT_SLASH_GT = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_EQ = 12,
  anon_sym_DOT_DOT_DOT = 13,
  aux_sym_python_expression_token1 = 14,
  aux_sym_python_expression_token2 = 15,
  sym_element_name = 16,
  sym_attribute_name = 17,
  anon_sym_SQUOTE = 18,
  aux_sym_attribute_string_value_token1 = 19,
  anon_sym_DQUOTE = 20,
  aux_sym_attribute_string_value_token2 = 21,
  sym_source_file = 22,
  sym_python_code = 23,
  sym_content = 24,
  sym_jsx_element = 25,
  sym_jsx_fragment = 26,
  sym_jsx_expression = 27,
  sym_jsx_attribute = 28,
  sym_jsx_spread_attribute = 29,
  sym_python_expression = 30,
  sym_attribute_string_value = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_python_code_repeat1 = 33,
  aux_sym_content_repeat1 = 34,
  aux_sym_jsx_element_repeat1 = 35,
  aux_sym_jsx_element_repeat2 = 36,
  aux_sym_python_expression_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_python_code_token1] = "python_code_token1",
  [aux_sym_python_code_token2] = "python_code_token2",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_LT_SLASH_GT] = "</>",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT_DOT_DOT] = "...",
  [aux_sym_python_expression_token1] = "python_expression_token1",
  [aux_sym_python_expression_token2] = "python_expression_token2",
  [sym_element_name] = "element_name",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_attribute_string_value_token1] = "attribute_string_value_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_attribute_string_value_token2] = "attribute_string_value_token2",
  [sym_source_file] = "source_file",
  [sym_python_code] = "python_code",
  [sym_content] = "content",
  [sym_jsx_element] = "jsx_element",
  [sym_jsx_fragment] = "jsx_fragment",
  [sym_jsx_expression] = "jsx_expression",
  [sym_jsx_attribute] = "jsx_attribute",
  [sym_jsx_spread_attribute] = "jsx_spread_attribute",
  [sym_python_expression] = "python_expression",
  [sym_attribute_string_value] = "attribute_string_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_python_code_repeat1] = "python_code_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_jsx_element_repeat1] = "jsx_element_repeat1",
  [aux_sym_jsx_element_repeat2] = "jsx_element_repeat2",
  [aux_sym_python_expression_repeat1] = "python_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_python_code_token1] = aux_sym_python_code_token1,
  [aux_sym_python_code_token2] = aux_sym_python_code_token2,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_LT_SLASH_GT] = anon_sym_LT_SLASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [aux_sym_python_expression_token1] = aux_sym_python_expression_token1,
  [aux_sym_python_expression_token2] = aux_sym_python_expression_token2,
  [sym_element_name] = sym_element_name,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_attribute_string_value_token1] = aux_sym_attribute_string_value_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_attribute_string_value_token2] = aux_sym_attribute_string_value_token2,
  [sym_source_file] = sym_source_file,
  [sym_python_code] = sym_python_code,
  [sym_content] = sym_content,
  [sym_jsx_element] = sym_jsx_element,
  [sym_jsx_fragment] = sym_jsx_fragment,
  [sym_jsx_expression] = sym_jsx_expression,
  [sym_jsx_attribute] = sym_jsx_attribute,
  [sym_jsx_spread_attribute] = sym_jsx_spread_attribute,
  [sym_python_expression] = sym_python_expression,
  [sym_attribute_string_value] = sym_attribute_string_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_python_code_repeat1] = aux_sym_python_code_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_jsx_element_repeat1] = aux_sym_jsx_element_repeat1,
  [aux_sym_jsx_element_repeat2] = aux_sym_jsx_element_repeat2,
  [aux_sym_python_expression_repeat1] = aux_sym_python_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_python_code_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_python_code_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_python_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_python_expression_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_element_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_string_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_string_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_python_code] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_element] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_spread_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_python_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_string_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_python_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jsx_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jsx_element_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_python_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 6,
  [12] = 5,
  [13] = 7,
  [14] = 8,
  [15] = 10,
  [16] = 9,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 17,
  [29] = 20,
  [30] = 30,
  [31] = 30,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 33,
  [36] = 34,
  [37] = 32,
  [38] = 22,
  [39] = 23,
  [40] = 24,
  [41] = 26,
  [42] = 21,
  [43] = 27,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 23,
  [52] = 52,
  [53] = 53,
  [54] = 47,
  [55] = 47,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 56,
  [64] = 64,
  [65] = 59,
  [66] = 66,
  [67] = 66,
  [68] = 60,
  [69] = 58,
  [70] = 59,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 72,
  [76] = 76,
  [77] = 74,
  [78] = 78,
  [79] = 79,
  [80] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 38,
        '\'', 36,
        '.', 2,
        '/', 7,
        '<', 20,
        '=', 29,
        '>', 21,
        '{', 27,
        '}', 28,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == '.') ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(17);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == '<') ADVANCE(18);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(28);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(32);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 11:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '>') ADVANCE(15);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_python_code_token1);
      if (lookahead == '>') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_python_code_token1);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_SLASH_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_python_expression_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_python_expression_token2);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_element_name);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_attribute_string_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_attribute_string_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 10},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 37},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 39},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_python_code_token2] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [aux_sym_python_expression_token2] = ACTIONS(1),
    [sym_element_name] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(76),
    [sym_python_code] = STATE(3),
    [sym_content] = STATE(3),
    [sym_jsx_element] = STATE(3),
    [sym_jsx_fragment] = STATE(3),
    [sym_jsx_expression] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_python_code_repeat1] = STATE(18),
    [aux_sym_content_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_python_code_token1] = ACTIONS(5),
    [aux_sym_python_code_token2] = ACTIONS(7),
    [aux_sym_content_token1] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_GT] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      aux_sym_python_code_token1,
    ACTIONS(22), 1,
      aux_sym_python_code_token2,
    ACTIONS(25), 1,
      aux_sym_content_token1,
    ACTIONS(28), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_LT_GT,
    ACTIONS(34), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      aux_sym_content_repeat1,
    STATE(18), 1,
      aux_sym_python_code_repeat1,
    STATE(2), 6,
      sym_python_code,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_source_file_repeat1,
  [36] = 10,
    ACTIONS(5), 1,
      aux_sym_python_code_token1,
    ACTIONS(7), 1,
      aux_sym_python_code_token2,
    ACTIONS(9), 1,
      aux_sym_content_token1,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LT_GT,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      aux_sym_content_repeat1,
    STATE(18), 1,
      aux_sym_python_code_repeat1,
    STATE(2), 6,
      sym_python_code,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_source_file_repeat1,
  [72] = 8,
    ACTIONS(39), 1,
      aux_sym_content_token1,
    ACTIONS(42), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    ACTIONS(47), 1,
      anon_sym_LT_GT,
    ACTIONS(50), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(4), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [101] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(4), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [127] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH_GT,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(5), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [153] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(8), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [179] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(4), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [205] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(4), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [231] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(9), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [257] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      anon_sym_LT_SLASH_GT,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(12), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [283] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      anon_sym_LT_SLASH_GT,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(4), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [309] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(14), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [335] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(4), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [361] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(16), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [387] = 7,
    ACTIONS(55), 1,
      aux_sym_content_token1,
    ACTIONS(57), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LT_GT,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(81), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      aux_sym_content_repeat1,
    STATE(4), 5,
      sym_content,
      sym_jsx_element,
      sym_jsx_fragment,
      sym_jsx_expression,
      aux_sym_jsx_element_repeat2,
  [413] = 4,
    ACTIONS(87), 1,
      aux_sym_content_token1,
    STATE(20), 1,
      aux_sym_content_repeat1,
    ACTIONS(85), 2,
      aux_sym_python_code_token2,
      anon_sym_LT,
    ACTIONS(83), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [430] = 5,
    ACTIONS(91), 1,
      aux_sym_python_code_token1,
    ACTIONS(93), 1,
      aux_sym_python_code_token2,
    STATE(19), 1,
      aux_sym_python_code_repeat1,
    ACTIONS(95), 2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [449] = 5,
    ACTIONS(99), 1,
      aux_sym_python_code_token1,
    ACTIONS(102), 1,
      aux_sym_python_code_token2,
    STATE(19), 1,
      aux_sym_python_code_repeat1,
    ACTIONS(105), 2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [468] = 4,
    ACTIONS(111), 1,
      aux_sym_content_token1,
    STATE(20), 1,
      aux_sym_content_repeat1,
    ACTIONS(109), 2,
      aux_sym_python_code_token2,
      anon_sym_LT,
    ACTIONS(107), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [485] = 2,
    ACTIONS(116), 3,
      aux_sym_python_code_token2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [497] = 2,
    ACTIONS(120), 3,
      aux_sym_python_code_token2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [509] = 2,
    ACTIONS(124), 3,
      aux_sym_python_code_token2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [521] = 2,
    ACTIONS(128), 3,
      aux_sym_python_code_token2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [533] = 5,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(135), 1,
      sym_attribute_name,
    STATE(46), 1,
      sym_jsx_spread_attribute,
    ACTIONS(130), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(25), 2,
      sym_jsx_attribute,
      aux_sym_jsx_element_repeat1,
  [551] = 2,
    ACTIONS(140), 3,
      aux_sym_python_code_token2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [563] = 2,
    ACTIONS(144), 3,
      aux_sym_python_code_token2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [575] = 4,
    ACTIONS(146), 1,
      aux_sym_content_token1,
    STATE(29), 1,
      aux_sym_content_repeat1,
    ACTIONS(85), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(83), 3,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [591] = 4,
    ACTIONS(148), 1,
      aux_sym_content_token1,
    STATE(29), 1,
      aux_sym_content_repeat1,
    ACTIONS(109), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(107), 3,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [607] = 6,
    ACTIONS(151), 1,
      anon_sym_GT,
    ACTIONS(153), 1,
      anon_sym_SLASH_GT,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      sym_attribute_name,
    STATE(46), 1,
      sym_jsx_spread_attribute,
    STATE(35), 2,
      sym_jsx_attribute,
      aux_sym_jsx_element_repeat1,
  [627] = 6,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      sym_attribute_name,
    ACTIONS(159), 1,
      anon_sym_GT,
    ACTIONS(161), 1,
      anon_sym_SLASH_GT,
    STATE(46), 1,
      sym_jsx_spread_attribute,
    STATE(33), 2,
      sym_jsx_attribute,
      aux_sym_jsx_element_repeat1,
  [647] = 2,
    ACTIONS(165), 3,
      aux_sym_python_code_token2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(163), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [659] = 6,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      sym_attribute_name,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_SLASH_GT,
    STATE(46), 1,
      sym_jsx_spread_attribute,
    STATE(25), 2,
      sym_jsx_attribute,
      aux_sym_jsx_element_repeat1,
  [679] = 2,
    ACTIONS(173), 3,
      aux_sym_python_code_token2,
      aux_sym_content_token1,
      anon_sym_LT,
    ACTIONS(171), 4,
      ts_builtin_sym_end,
      aux_sym_python_code_token1,
      anon_sym_LT_GT,
      anon_sym_LBRACE,
  [691] = 6,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      sym_attribute_name,
    ACTIONS(175), 1,
      anon_sym_GT,
    ACTIONS(177), 1,
      anon_sym_SLASH_GT,
    STATE(46), 1,
      sym_jsx_spread_attribute,
    STATE(25), 2,
      sym_jsx_attribute,
      aux_sym_jsx_element_repeat1,
  [711] = 2,
    ACTIONS(173), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(171), 4,
      aux_sym_content_token1,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [722] = 2,
    ACTIONS(165), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(163), 4,
      aux_sym_content_token1,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [733] = 2,
    ACTIONS(120), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(118), 4,
      aux_sym_content_token1,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [744] = 2,
    ACTIONS(124), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(122), 4,
      aux_sym_content_token1,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [755] = 2,
    ACTIONS(128), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(126), 4,
      aux_sym_content_token1,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [766] = 2,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(138), 4,
      aux_sym_content_token1,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [777] = 2,
    ACTIONS(116), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(114), 4,
      aux_sym_content_token1,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [788] = 2,
    ACTIONS(144), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
    ACTIONS(142), 4,
      aux_sym_content_token1,
      anon_sym_LT_GT,
      anon_sym_LT_SLASH_GT,
      anon_sym_LBRACE,
  [799] = 4,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    STATE(49), 2,
      sym_jsx_expression,
      sym_attribute_string_value,
  [813] = 2,
    ACTIONS(187), 1,
      sym_attribute_name,
    ACTIONS(185), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_LBRACE,
  [822] = 2,
    ACTIONS(191), 1,
      sym_attribute_name,
    ACTIONS(189), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_LBRACE,
  [831] = 3,
    STATE(52), 1,
      aux_sym_python_expression_repeat1,
    STATE(59), 1,
      sym_python_expression,
    ACTIONS(193), 2,
      aux_sym_python_expression_token1,
      aux_sym_python_expression_token2,
  [842] = 3,
    STATE(52), 1,
      aux_sym_python_expression_repeat1,
    STATE(71), 1,
      sym_python_expression,
    ACTIONS(193), 2,
      aux_sym_python_expression_token1,
      aux_sym_python_expression_token2,
  [853] = 2,
    ACTIONS(197), 1,
      sym_attribute_name,
    ACTIONS(195), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_LBRACE,
  [862] = 2,
    ACTIONS(201), 1,
      sym_attribute_name,
    ACTIONS(199), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_LBRACE,
  [871] = 2,
    ACTIONS(124), 1,
      sym_attribute_name,
    ACTIONS(122), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_LBRACE,
  [880] = 4,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    ACTIONS(205), 1,
      aux_sym_python_expression_token1,
    ACTIONS(207), 1,
      aux_sym_python_expression_token2,
    STATE(53), 1,
      aux_sym_python_expression_repeat1,
  [893] = 4,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    ACTIONS(211), 1,
      aux_sym_python_expression_token1,
    ACTIONS(214), 1,
      aux_sym_python_expression_token2,
    STATE(53), 1,
      aux_sym_python_expression_repeat1,
  [906] = 3,
    STATE(52), 1,
      aux_sym_python_expression_repeat1,
    STATE(65), 1,
      sym_python_expression,
    ACTIONS(193), 2,
      aux_sym_python_expression_token1,
      aux_sym_python_expression_token2,
  [917] = 3,
    STATE(52), 1,
      aux_sym_python_expression_repeat1,
    STATE(70), 1,
      sym_python_expression,
    ACTIONS(193), 2,
      aux_sym_python_expression_token1,
      aux_sym_python_expression_token2,
  [928] = 1,
    ACTIONS(217), 1,
      sym_element_name,
  [932] = 1,
    ACTIONS(219), 1,
      aux_sym_attribute_string_value_token1,
  [936] = 1,
    ACTIONS(221), 1,
      anon_sym_GT,
  [940] = 1,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
  [944] = 1,
    ACTIONS(225), 1,
      anon_sym_GT,
  [948] = 1,
    ACTIONS(227), 1,
      aux_sym_attribute_string_value_token2,
  [952] = 1,
    ACTIONS(229), 1,
      anon_sym_SQUOTE,
  [956] = 1,
    ACTIONS(231), 1,
      sym_element_name,
  [960] = 1,
    ACTIONS(229), 1,
      anon_sym_DQUOTE,
  [964] = 1,
    ACTIONS(233), 1,
      anon_sym_RBRACE,
  [968] = 1,
    ACTIONS(235), 1,
      anon_sym_GT,
  [972] = 1,
    ACTIONS(237), 1,
      anon_sym_GT,
  [976] = 1,
    ACTIONS(239), 1,
      anon_sym_GT,
  [980] = 1,
    ACTIONS(241), 1,
      anon_sym_GT,
  [984] = 1,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
  [988] = 1,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
  [992] = 1,
    ACTIONS(247), 1,
      sym_element_name,
  [996] = 1,
    ACTIONS(249), 1,
      sym_element_name,
  [1000] = 1,
    ACTIONS(251), 1,
      sym_element_name,
  [1004] = 1,
    ACTIONS(253), 1,
      sym_element_name,
  [1008] = 1,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
  [1012] = 1,
    ACTIONS(257), 1,
      sym_element_name,
  [1016] = 1,
    ACTIONS(259), 1,
      anon_sym_DOT_DOT_DOT,
  [1020] = 1,
    ACTIONS(261), 1,
      anon_sym_EQ,
  [1024] = 1,
    ACTIONS(263), 1,
      sym_element_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 101,
  [SMALL_STATE(6)] = 127,
  [SMALL_STATE(7)] = 153,
  [SMALL_STATE(8)] = 179,
  [SMALL_STATE(9)] = 205,
  [SMALL_STATE(10)] = 231,
  [SMALL_STATE(11)] = 257,
  [SMALL_STATE(12)] = 283,
  [SMALL_STATE(13)] = 309,
  [SMALL_STATE(14)] = 335,
  [SMALL_STATE(15)] = 361,
  [SMALL_STATE(16)] = 387,
  [SMALL_STATE(17)] = 413,
  [SMALL_STATE(18)] = 430,
  [SMALL_STATE(19)] = 449,
  [SMALL_STATE(20)] = 468,
  [SMALL_STATE(21)] = 485,
  [SMALL_STATE(22)] = 497,
  [SMALL_STATE(23)] = 509,
  [SMALL_STATE(24)] = 521,
  [SMALL_STATE(25)] = 533,
  [SMALL_STATE(26)] = 551,
  [SMALL_STATE(27)] = 563,
  [SMALL_STATE(28)] = 575,
  [SMALL_STATE(29)] = 591,
  [SMALL_STATE(30)] = 607,
  [SMALL_STATE(31)] = 627,
  [SMALL_STATE(32)] = 647,
  [SMALL_STATE(33)] = 659,
  [SMALL_STATE(34)] = 679,
  [SMALL_STATE(35)] = 691,
  [SMALL_STATE(36)] = 711,
  [SMALL_STATE(37)] = 722,
  [SMALL_STATE(38)] = 733,
  [SMALL_STATE(39)] = 744,
  [SMALL_STATE(40)] = 755,
  [SMALL_STATE(41)] = 766,
  [SMALL_STATE(42)] = 777,
  [SMALL_STATE(43)] = 788,
  [SMALL_STATE(44)] = 799,
  [SMALL_STATE(45)] = 813,
  [SMALL_STATE(46)] = 822,
  [SMALL_STATE(47)] = 831,
  [SMALL_STATE(48)] = 842,
  [SMALL_STATE(49)] = 853,
  [SMALL_STATE(50)] = 862,
  [SMALL_STATE(51)] = 871,
  [SMALL_STATE(52)] = 880,
  [SMALL_STATE(53)] = 893,
  [SMALL_STATE(54)] = 906,
  [SMALL_STATE(55)] = 917,
  [SMALL_STATE(56)] = 928,
  [SMALL_STATE(57)] = 932,
  [SMALL_STATE(58)] = 936,
  [SMALL_STATE(59)] = 940,
  [SMALL_STATE(60)] = 944,
  [SMALL_STATE(61)] = 948,
  [SMALL_STATE(62)] = 952,
  [SMALL_STATE(63)] = 956,
  [SMALL_STATE(64)] = 960,
  [SMALL_STATE(65)] = 964,
  [SMALL_STATE(66)] = 968,
  [SMALL_STATE(67)] = 972,
  [SMALL_STATE(68)] = 976,
  [SMALL_STATE(69)] = 980,
  [SMALL_STATE(70)] = 984,
  [SMALL_STATE(71)] = 988,
  [SMALL_STATE(72)] = 992,
  [SMALL_STATE(73)] = 996,
  [SMALL_STATE(74)] = 1000,
  [SMALL_STATE(75)] = 1004,
  [SMALL_STATE(76)] = 1008,
  [SMALL_STATE(77)] = 1012,
  [SMALL_STATE(78)] = 1016,
  [SMALL_STATE(79)] = 1020,
  [SMALL_STATE(80)] = 1024,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jsx_element_repeat2, 2, 0, 0), SHIFT_REPEAT(28),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jsx_element_repeat2, 2, 0, 0), SHIFT_REPEAT(56),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_jsx_element_repeat2, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jsx_element_repeat2, 2, 0, 0), SHIFT_REPEAT(11),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_jsx_element_repeat2, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jsx_element_repeat2, 2, 0, 0), SHIFT_REPEAT(54),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_code, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_python_code, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_python_code_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_python_code_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_python_code_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_python_code_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_element, 7, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_element, 7, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_fragment, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_fragment, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_expression, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_expression, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_element, 4, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_element, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_jsx_element_repeat1, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jsx_element_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jsx_element_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_element, 6, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_element, 6, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_element, 8, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_element, 8, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_fragment, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_fragment, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_element, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_element, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_spread_attribute, 4, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_spread_attribute, 4, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_attribute, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_attribute, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_attribute, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_attribute, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_string_value, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_string_value, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_expression, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_python_expression_repeat1, 2, 0, 0),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_python_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [214] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_python_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [255] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pyjsx(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
